name: amap_map_fluttify
description: An `Amap` Map Component, Powered By `Fluttify` Compiler, A Dart Bindings Generator For Native SDK.
version: 1.4.1
author: yohom <yohombao@qq.com>
homepage: https://github.com/fluttify-project/amap_map_fluttify
publish_to: 'none'

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  amap_core_fluttify: ^0.11.0
  amap_location_fluttify: ^0.16.0
  amap_search_fluttify: ^0.13.0
  url_launcher: ^5.4.2
  foundation_fluttify: ^0.9.2
  core_location_fluttify: ^0.4.0

#dependency_overrides:
#  foundation_fluttify:
#    path: /Users/yohom/Github/Me/All/fluttify/fluttify_infra/foundation_fluttify

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.amap_map_fluttify
        pluginClass: AmapMapFluttifyPlugin
      ios:
        pluginClass: AmapMapFluttifyPlugin
  assets:
    - images/